from pathlib import Path
import pandas as pd
import numpy as np

# Global paths
out_dir=Path(config['out_dir'])
logs=Path(config['log_dir'])

include: "rules/prep.smk"
include: "rules/apt.smk"
include: "rules/bcftools.smk"

rule all:
    input:
        vcf_file=out_dir/"combined.hg38.bcf"


