# Workflow profile

# Conda settings
use-conda: True
conda-frontend: mamba

# General settings
verbose: False
keep-going: True
rerun-incomplete: True
latency-wait: 30
retries: 0

# Resource settings per rule
set-resources:
  map_samples:
    threads: 1
    mem: "4GB"
    runtime: 1
  list_cel_files:
    threads: 1
    mem: "4GB"
    runtime: 1
  apt:
    threads: 10
    mem: "16GB"
    runtime: 20
  make_vcf:
    mem: "12GB"
    runtime: 20
  otv_caller:
    threads: 20
    mem: "4GB"
    runtime: 30
  ps_metrics:
    threads: 10
    mem: "8GB"
    runtime: 5
  ps_classification:
    threads: 10
    mem: "8GB"
    runtime: 10
  format_vcf:
    threads: 1
    mem: "8GB"
    runtime: 20
  sort_vcf:
    threads: 1
    mem: "8GB"
    runtime: 20
  index_vcf:
    threads: 1
    mem: "8GB"
    runtime: 10
  liftover:
    threads: 1
    mem: "8GB"
    runtime: 20