# This config file hows an example of how to configure the genotyping workflow
# Edit as appropriate to the dataset to which the workflow will be applied
# Typically refs (=references) can be left unchanged

# Dependencies
deps:
  # Sample sheet. See README for column specifications
  samples: "config/genotyping/samples.csv"
  # Directory containing .CEL files
  cel: "data/snp/microarray"

# Outputs
outs:
  vcf_hg19: "data/snp/genotyping/donors.hg19.vcf"
  vcf_hg38: "data/snp/genotyping/donors.hg38.vcf"
  psam: "data/snp/genotyping/test.psam"
  id_map: "data/snp/genotyping/id_map.tsv"
  logs: "logs/genotyping"

# References
refs:
  genomes:
    hg19: "resources/genomes/hg19/hg19.fa.gz"
    hg38: "resources/genomes/refdata-gex-GRCh38-2020-A/fasta/genome.fa"
    chain: "resources/liftover/hg19ToHg38.over.chain.gz"
  apt:
    arg_file: "resources/genotyping/annotation/Axiom_UKB_WCSG.r5.apt-genotype-axiom.AxiomCN_GT1.apt2.xml"
    ps2snp: "resources/genotyping/annotation/Axiom_UKB_WCSG.r5.ps2snp_map.ps"
    annotation: "resources/genotyping/annotation/Axiom_UKB_WCSG.na35.annot.db"
