# This config file is used for running the workflow on the test dataset

# Dependencies
deps:
  # Sample sheet. See README for column specifications
  samples: config/samples.csv
  genomes:
    hg19: "resources/genomes/hg19/hg19.fa.gz"
    hg38: "resources/genomes/refdata-gex-GRCh38-2020-A/fasta/genome.fa"
    chain: "resources/liftover/hg19ToHg38.over.chain.gz"
  apt:
    arg_file: "resources/genotyping/annotation/Axiom_UKB_WCSG.r5.apt-genotype-axiom.AxiomCN_GT1.apt2.xml"
    ps2snp: "resources/genotyping/annotation/Axiom_UKB_WCSG.r5.ps2snp_map.ps"
    annotation: "resources/genotyping/annotation/Axiom_UKB_WCSG.na35.annot.db"

# Outputs
outs:
  vcf_hg19: "test/results/final.hg19.vcf"
  vcf_hg38: "test/results/final.hg38.vcf"
  psam: "test/results/final.psam"
  logs: "logs/genotyping"